# Generated by Django 4.1.3 on 2022-11-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termdates',
            name='name',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
