# Generated by Django 4.1.3 on 2022-12-04 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Renewal',
        ),
    ]
