# Generated by Django 4.1.3 on 2022-11-24 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='availability',
        ),
        migrations.AddField(
            model_name='lesson',
            name='availabilityDay',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='availabilityTime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
