# Generated by Django 4.1.3 on 2022-11-30 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_termdates_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.termdates'),
        ),
        migrations.AlterField(
            model_name='termdates',
            name='name',
            field=models.CharField(default='default', max_length=50, unique=True),
        ),
    ]
