# Generated by Django 4.1.3 on 2022-11-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_lesson_availability_lesson_availabilityday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='availabilityDay',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='availabilityTime',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='desiredInterval',
            field=models.CharField(max_length=5),
        ),
    ]
