# Generated by Django 4.1.3 on 2022-11-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='availability',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='desiredInterval',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='furtherInfo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lessons',
            field=models.IntegerField(),
        ),
    ]
