# Generated by Django 4.1.3 on 2022-11-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='availability',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='desiredInterval',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='furtherInfo',
            field=models.TextField(max_length=2),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lessons',
            field=models.IntegerField(max_length=2),
        ),
    ]
