# Generated by Django 4.1.3 on 2022-11-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='furtherInfo',
            field=models.TextField(),
        ),
    ]
