# Generated by Django 4.1.3 on 2022-12-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_renewal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lessons',
            field=models.IntegerField(),
        ),
    ]
