# Generated by Django 4.1.3 on 2022-12-01 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lesson_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renewal',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='renewal',
            name='renew',
        ),
        migrations.AddField(
            model_name='renewal',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.termdates'),
        ),
    ]
