# Generated by Django 4.1.3 on 2022-11-25 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_lesson_availabilityday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lessons',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
