# Generated by Django 4.1.3 on 2022-11-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_lesson_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
