# Generated by Django 4.1.3 on 2022-11-25 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_alter_lesson_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lessons',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(4)]),
        ),
    ]
