# Generated by Django 4.1.3 on 2022-12-03 15:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_alter_lesson_lessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='termdates',
            name='weeks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lessons',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(4)]),
        ),
    ]
