# Generated by Django 4.1.3 on 2022-12-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_termdates_weeks_alter_lesson_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lessons',
            field=models.IntegerField(),
        ),
    ]
