# Generated by Django 4.1.3 on 2022-12-03 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_alter_lesson_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termdates',
            name='weeks',
            field=models.IntegerField(default='default', unique=True),
        ),
    ]
