# Generated by Django 4.1.3 on 2022-12-03 23:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_alter_termdates_weeks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lessons',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='termdates',
            name='weeks',
            field=models.IntegerField(),
        ),
    ]
